
export default new Map([
["src/content/services/aile-ve-bosanma.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Faile-ve-bosanma.mdx&astroContentModuleFlag=true")],
["src/content/services/bilisim-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fbilisim-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/services/icra-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Ficra-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/services/ceza-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fceza-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/services/idare-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fidare-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/services/gayrimenkul-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fgayrimenkul-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/services/ticaret-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fticaret-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/blog/cocugun-cinsel-istismari-ve-zincirleme-suc-hukumleri-yargitay-karari.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fcocugun-cinsel-istismari-ve-zincirleme-suc-hukumleri-yargitay-karari.mdx&astroContentModuleFlag=true")],
["src/content/blog/hizmet-tespiti-davasi-yargitay-karari-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fhizmet-tespiti-davasi-yargitay-karari-2025.mdx&astroContentModuleFlag=true")],
["src/content/services/is-hukuku.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fis-hukuku.mdx&astroContentModuleFlag=true")],
["src/content/blog/sgk-recete-uyusmazligi-yargitay-karari-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fsgk-recete-uyusmazligi-yargitay-karari-2025.mdx&astroContentModuleFlag=true")],
["src/content/blog/radarda-10-tolerans-donemi-bitti-yeni-trafik-cezasi-sistemi-nasil-isleyecek.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fradarda-10-tolerans-donemi-bitti-yeni-trafik-cezasi-sistemi-nasil-isleyecek.mdx&astroContentModuleFlag=true")],
["src/content/services/sirket-danismanligi.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fservices%2Fsirket-danismanligi.mdx&astroContentModuleFlag=true")],
["src/content/blog/kasten-oldurmeye-tesebbus-ceza-indirimi-yargitay-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fkasten-oldurmeye-tesebbus-ceza-indirimi-yargitay-2025.mdx&astroContentModuleFlag=true")],
["src/content/blog/yargitay-karari-belirli-sureli-tahliye-zamani.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fyargitay-karari-belirli-sureli-tahliye-zamani.mdx&astroContentModuleFlag=true")],
["src/content/blog/tapu-iptali-ve-tescil-fiili-taksim-yargitay-karari-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Ftapu-iptali-ve-tescil-fiili-taksim-yargitay-karari-2025.mdx&astroContentModuleFlag=true")],
["src/content/blog/zilyetlik-imar-plani-yargitay-karari-2025.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fblog%2Fzilyetlik-imar-plani-yargitay-karari-2025.mdx&astroContentModuleFlag=true")]]);
		